#!/bin/bash

DISTRO=$1

FOLDERS="alacritty bin bspwm gnupg nvim polybar rclone spotifyd starship sxhkd systemd_user tmux x zsh"

pushd $DOTFILES
for folder in $FOLDERS;do
  stow -D $folder
  stow $folder
done
popd
