---

#- name: Clone dotfiles repo
#  git:
#    repo: "https://gitlab.com/andrewkreuzer/dotfiles.git"
#    dest: "{{ dotfile_location }}"
#  become: false

- name: Create .config folder
  file:
    path: "{{ config_folder }}"
    state: directory
    mode: 0755

- name: Setup .config links
  file:
    src: "{{ dotfile_location }}/{{ item }}"
    dest: "{{ config_folder }}/{{ item }}"
    state: link
    mode: 755
  become: false
  with_items: "{{ dotfiles_config }}"

- name: Setup $HOME links
  file:
    src: "{{ dotfile_location }}/{{ item }}"
    dest: "{{ home_folder }}/{{ item }}"
    state: link
    mode: 755
  become: false
  with_items: "{{ dotfiles_home }}"

- name: remove default .zprofile
  file:
    path: "{{ home_folder }}.zprofile"
    state: absent

- name: copy .zprofile
  file:
    src: "{{ dotfile_location }}/.profile"
    dest: "{{ home_folder }}/.zprofile"
    state: link
    mode: 755
  become: false
