#! /bin/sh


polybar=$HOME/.config/polybar/launch.sh

pkill sxhkd
sxhkd &

# Polybar
if [ -x $polybar ]; then
    . $polybar
fi

#                   ____________
#                   |          |
#  ________________ |          |
# |                ||          |
# |                ||          |
# |     Main       ||   Vert   |
# |                ||          |
# |________________||          |
#                   |          |
#                   |__________|

# Main Monitor
bspc monitor DP-1 -d I II III IV V
# Vertical Monior
bspc monitor DVI-I-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

# Border colors
bspc config normal_border_color "#c0c0c0"
bspc config active_border_color "#c0c0c0"
bspc config focused_border_color "#fffff"
bspc config presel_feedback_color "#00000"

bspc config bottom_padding 5
bspc config top_padding 25

bspc config split_ratio          0.50
#bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus 		  true

# Scratchpad
bspc rule -a scratchpad sticky=on \
                        state=floating \
                        hidden=on \
                        monitor=DP-1 \
                        rectangle=500x170+20+1300
pkill -f scratchpad
alacritty --class Alacritty,scratchpad -e "$HOME/.config/scripts/bspwm_scratchpad.sh" &

# Background
feh --no-fehbg --bg-fill ~/.config/background.jpg
