#! /bin/sh

sxhkd &

# Start Polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

# Border colors
bspc config normal_border_color "#c0c0c0"
bspc config active_border_color "#c0c0c0"
bspc config focused_border_color "#fffff"
bspc config presel_feedback_color "#00000"

bspc config bottom_padding 0
bspc config top_padding 25

bspc config split_ratio          0.50
#bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus 		  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Scratchpad
bspc rule -a scratchpad sticky=on state=floating hidden=off
alacritty --class scratchpad -e "zsh -i" &

# Background
feh --no-fehbg --bg-fill ~/.config/background.jpg
