#! /bin/sh
polybar=$HOME/.config/polybar/launch.sh

pkill sxhkd
sxhkd &

# Polybar
if [ -x $polybar ]; then
    . $polybar
fi

#                   ____________
#                   |          |
#  ________________ |          |
# |                ||          |
# |                ||          |
# |     Main       ||   Vert   |
# |                ||          |
# |________________||          |
#                   |          |
#                   |__________|

# Main Monitor
bspc monitor DP-1 -d 1 2 3 4 5
# Vertical Monior
bspc monitor DVI-I-1 -d 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           10

# Border colors
bspc config normal_border_color "#0A0E14"
bspc config active_border_color "#0A0E14"
bspc config focused_border_color "#B3B1AD"
bspc config presel_feedback_color "#00000"

bspc config bottom_padding 5
bspc config top_padding 30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true
bspc config single_monocle       true

# Scratchpad
bspc rule -a scratchpad_left  monitor=DP-1 \
                              sticky=on \
                              state=floating \
                              hidden=on \
                              rectangle=500x170+20+1300

bspc rule -a scratchpad_right monitor=DVI-I-1 \
                              sticky=on \
                              state=floating \
                              hidden=on \
                              rectangle=500x200+1300+20

pkill -f scratchpad_left
pkill -f scratchpad_right
alacritty --class Alacritty,scratchpad_left -e "$HOME/.local/bin/bspwm_scratchpad_left.sh" &
alacritty --class Alacritty,scratchpad_right -e "$HOME/.local/bin/bspwm_scratchpad_right.sh" &

# Background
feh --no-fehbg --bg-fill ~/.config/background.jpg
