home_folder: "$HOME"
dotfile_location: "{{ home_folder }}/dotfiles"
config_folder: "{{ home_folder }}/.config"

dotfiles_config:
  - alacritty
  - nvim
  - spotifyd 
  - tmux
  - zsh

dotfiles_home:
  - .profile

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_apps:
  - docker
  - postman
  - firefox
  - slack
  - vagrant
  - virtualbox

homebrew_installed_packages:
  # - alacritty
  - awscli
  - docker-compose
  - fzf
  - git
  - gpg
  - go
  - hopenpgp-tools
  - node
  - nvim
  - nvm
  - openssl
  - pass
  - ripgrep
  - rust
  - spotifyd
  - spotify-tui
  - terraform
  - tealdeer
  - tmux
  - wget
  - yubikey-personalization
  - ykman
  - zoxide
  - zsh
  - zsh-syntax-highlighting

