---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.homebrew
      when: ansible_distribution == 'MacOSX'
    - role: dotfiles

  tasks:
    - name: Change shell to zsh
      user:
        name: akreuzer
        shell: /bin/zsh
      become: yes
